blank_issues_enabled: false
contact_links:
  - name: 💬 Start a discussion
    url: https://github.com/OmniSafeAI/safety-gymnasium/discussions/new
    about: Please ask and answer questions here if unsure.
